# Forma de Newton para o polinômio interpolador

## $ \S 1 $ Introdução

Apesar de simples, a forma de Lagrange para o polinômio interpolador não é
ideal do ponto de vista computacional. Neste caderno apresentaremos uma
outra forma, mais eficiente, para determinação deste mesmo polinômio, que
remonta a Isaac Newton (1643–1727).

A principal diferença entre as duas formas aparece quando precisamos adicionar
um novo dado ao conjunto original. Pelo método de Lagrange, precisamos
recalcular o polinômio. Já utilizando o método de Newton, podemos simplesmente
adicionar um termo ao polinômio existente. Isto o torna mais apropriado quando
os pontos a serem interpolados são atualizados freqüentemente.


__Exemplo 1:__ Para ilustrar a idéia por trás do método de Newton, considere
inicialmente o polinômio de grau $ \le 2 $ que interpola $ (x_0, y_0) $,
$ (x_1, y_1) $ e $ (x_2 ,y_2) $. Para que ele passe pelo primeiro ponto, podemos
tomá-lo da forma:
$$
    p(x) = y_0 + (x - x_0)\,p_1(x)\,,
$$
onde $ p_1 $ tem grau $ \le 1 $. Agora o problema original foi reduzido a 
outro mais fácil: o de se encontrar um polinômio interpolador de grau $ \le 1 $.
Efetuando a substituição dos outros dois dados, vemos que o gráfico de
$ p_1 $ precisa passar por
\begin{equation*}
\big(x_1, \nabla y_1 \big) \quad \text{e} \quad \big(x_2, \nabla y_2 \big)\,,
\tag{1}
\end{equation*}
onde por definição
$$
    \nabla y_i := \frac{y_i - y_0}{x_i - x_0} \qquad (i = 1,\,2)\,.
$$
Estas quantidades são chamadas de _diferenças divididas_ e serão
discutidas detalhadamente logo abaixo. Para encontrar $ p_1 $, podemos
utlizar a mesma estratégia. De modo que ele passe pelo primeiro ponto em
\eqref{E:data}, podemos escrevê-lo na forma
$$
p_1(x) = \nabla y_1 + (x - x_1)\,p_0(x)
$$
onde $ p_0 $ é um polinômio de grau $ \le 0 $, ou seja, constante.
Finalmente, substituindo o segundo dado em \eqref{E:data} aqui,
deduzimos que o valor desta constante deve ser
$$
\frac{\nabla y_2 - \nabla y_1}{x_2 - x_1} =: \nabla^2 y_2\,.
$$
Esta última quantidade é uma _diferença dividida de segunda ordem_.
Resumindo, encontramos que
$$
p(x) = y_0 + \nabla y_1\,(x - x_0) + \nabla^2 y_2\,(x - x_0)(x - x_1)\,.
$$
Generalizando esta conta a um grau arbitrário, podemos deduzir que o
polinômio interpolador pode ser expresso de maneira inteiramente análoga, em que
o $ k $-ésimo coeficiente é dado pela diferença dividida de ordem superior $
\nabla^k y_k $.  Estas diferenças divididas que apareceram de maneira natural
aqui são análogas às sucessivas derivadas de uma função, exceto que elas
envolvem vários pontos. 

__Problema 1:__ Use a mesma estratégia para expressar o polinômio interpolador dos dados
$$
(x_0,\, y_0),\quad (x_1,\,y_1),\quad (x_{2},\,y_{2}),\quad (x_{3},\, y_{3})
$$
na forma
$$
p(x) = a_0 + a_1(x - x_0) + a_2(x - x_0)(x - x_1) + a_3(x - x_0)(x - x_1)(x - x_2)\,.
$$
Em particular, observe que os coeficientes $ a_0 $, $ a_1 $ e $ a_2 $ são dados pelas
mesmas fórmulas que acima.

## $ \S 2 $ Diferenças divididas

Sejam $ x_0,\, x_1, \cdots,\,x_{N} \in \mathbb R $ _distintos_ 
e $ y_0,\,y_1,\, \cdots,\, y_{N} \in \mathbb R $ valores quaisquer.  As
__diferenças divididas__ de $ f $ associadas a eles são definidas
recursivamente:

* As diferenças divididas de $ 0 $-ésima ordem são simplesmente os $ y_i $:
$$
\nabla^0 y_i = y_i \qquad (i = 0,\,1, \cdots,\, N)\,.
$$
* As _diferenças divididas de primeira ordem_ são dadas por
$$
\nabla^1 y_i = \frac{y_i - y_0}{x_i - x_0} \qquad (i = 1, \cdots,\, N)\,.
$$
* Em geral, as diferenças divididas de $ k $-ésima ordem (onde $ k \le N $)
são dadas por
$$
\boxed{\ \nabla^k y_i = \frac{\nabla^{k - 1}y_i - \nabla^{k - 1} y_{k - 1}}{x_i - x_{k - 1}}
\qquad (i = k, \cdots,\, N)\ }
$$ 


## $ \S 3 $ Tabela de diferenças divididas

As diferenças divididas de ordens sucessivas podem ser calculadas de maneira
eficiente e sistemática em forma tabular. Para construir a tabela, começamos
listando os valores $ x_i $ e $ y_i $ nas duas primeiras colunas. A cada
passo, utilizamos os valores na coluna atual e na dos $ x_i $ para
preencher a próxima coluna. 

__Exemplo 2:__ Considere os seguintes pontos:
$$
(x_0, y_0) = (-3, 4), \quad  (x_1, y_1) = (-1, 2),\quad
(x_2, y_2) = (0, 0),\quad \text{e} \quad (x_3, y_3) = (2, 7)\,.
$$
A tabela de diferenças divididas para eles é dada por:
$$
\begin{array}{r|r|rrrr}
i & x_i & y_i & \nabla^1y_i & \nabla^2y_i & \nabla^3y_i \\
\hline
0 & -3 & 4 & & & \\
1 & -1 & 2 & -1 & & \\
2 & 0 & 0 & -4/3 & -1/3 & \\
3 & 2 & 9 & 1 & 2/3 & 1/2 \\
\end{array}
$$

No caso geral, _cada entrada não fornecida é igual à diferença entre a entrada
imediatamente à sua esquerda e a primeira entrada da coluna anterior, dividida
pela diferença entre as entradas correspondentes na coluna dos valores de_ $ x $.
Isto segue imediatamente da definição das diferenças divididas.

__Exemplo 3:__ Determine a tabela de diferenças divididas associada aos pontos abaixo:
$$
(x_0, y_0) = (-2, -8), \quad  (x_1, y_1) = (-1, -1), \quad
(x_2, y_2) = (0, 0), \quad  (x_3, y_3) = (1, 1) \quad
\text{e} \quad  (x_4, y_4) = (2, 8) \,.
$$

_Solução:_ Basta seguir o procedimento descrito acima. Para o cálculo
não é necessário considerar a coluna com os índices $ i $ (ela foi
incluída antes apenas como auxílio à compreensão do procedimento).
No nosso caso, temos:
$$
\begin{array}{r|rrrrr}
x_i & y_i & \nabla^1y_i & \nabla^2y_i & \nabla^3y_i & \nabla^4y_i \\
\hline
-2 & -8 & & & & \\
-1 & -1 & 7 & & & \\
0 & 0 & 4 & -3 & & \\
1 & 1 & 3 & -2 & 1 & \\
2 & 8 & 4 & -1 & 1 & 0 \\
\end{array}
$$

📝 Observe que a tabela de diferenças associada a uma lista de $ N + 1 $ pontos
tem dimensão $ (N + 1) \times (N + 1) $ se ignorarmos a coluna dos valores $ x $.

__Problema 2:__ Mostre que a tabela de diferenças divididas associada aos pontos
$$
(x_0, y_0) = (-3, 6), \quad (x_1, y_1) = (-1, 4), \quad (x_2, y_2) = (1, 2),
\quad (x_3, y_3) = (3, 0) \quad \text{e} \quad (x_4, y_4) = (5, -2)
$$
é dada por:
$$
\begin{array}{r|rrrrr}
x_i & y_i & \nabla^1y_i & \nabla^2y_i & \nabla^3y_i & \nabla^4y_i \\
\hline
-3 & 6 & & & & \\
-1 & 4 & -1 & & & \\
1 & 2 & -1 & 0 & & \\
3 & 0 & -1 & 0 & 0 & \\
5 & -2 & -1 & 0 & 0 & 0 \\
\end{array}
$$


__Problema 3:__ Verifique as entradas da tabela de diferenças divididas para a
função $ y = \sin x $ abaixo:
$$
\begin{array}{c|cccc}
x_i & y_i = \sin(x_i) & \nabla^1y_i & \nabla^2y_i & \nabla^3y_i \\
\hline
0 & 0 & & & \\
\frac{\pi}{3} & \frac{\sqrt{3}}{2} & \frac{3\sqrt{3}}{2\pi} & & \\
\frac{2\pi}{3} & \frac{\sqrt{3}}{2} & \frac{3\sqrt{3}}{4\pi} & -\frac{9\sqrt{3}}{4\pi^2} & \\
\pi & 0 & 0 & -\frac{9\sqrt{3}}{4\pi^2} & 0 \\
\end{array}
$$

k# $ \S 4 $ Forma de Newton para o polinômio interpolador

Como antes, seja $ p(x) $ o polinômio de grau $ \le N $ que interpola os
$ N + 1 $ pontos
$$
(x_0,\, y_0),\quad (x_1,\,y_1),\quad \cdots,\quad
(x_{N - 1},\,y_{N - 1}),\quad (x_{N},\, y_{N})\,.
$$
O __método de Newton__ ou __método das diferenças divididas__ para se determinar $ p $
envolve escrevê-lo na forma:
\begin{equation*}
p(x) = a_0 + a_1(x - x_0) + a_2 (x - x_0)(x - x_1) +
\cdots + a_N(x - x_0)(x - x_1) \cdots (x - x_{N})\,. \tag{2}
\end{equation*}
Esta é a chamada __forma__ (ou __fórmula__) __de Newton__ para o polinômio
interpolador.
Procedendo exatamente da mesma maneira que fizemos na $ \S 1 $ para um polinômio
de grau $ 2 $, encontramos que os coeficientes de $ p $ são dados por:
$$
\boxed{a_k = \nabla^k\vphantom{N^N_N} y_k \qquad (k = 0,\,1,\, \cdots,\, N)}
$$

📝 Trocando-se a ordem em que os pontos $ (x_k, y_k) $ são listados, a tabela
de diferenças divididas associada obviamente mudará, e portanto a expressão 
\eqref{E:expression} para $ p $ também.  Entretanto, como visto no caderno
anterior, o polinômio $ p $ resultante permanecerá o mesmo, já que (como
provado anteriormente) ele é único.

__Problema:__ Dados os pontos indicados, calcule a tabela de diferenças
divididas e encontre o polinômio interpolador usando o método de Newton.

(a) $ (2, 4),\ (0, 0), $ e $ (1, 1) $.

(b) $ (-1, -1) $, $ (0, 0) $, $ (1, 1) $ e $ (2, 8) $.

(c) $ (1,2) $, $ (3,4) $ e $ (4,0) $.



__Problema:__

(a) Aproveite a tabela de diferenças divididas do Problema 3 para determinar o
polinômio $ p $ que interpola a função $ y = \sin x $ em
$ x = 0,\, \frac{\pi}{3},\, \frac{2\pi}{3},\, \pi $.

(b) Aproxime $ \int_0^\pi \sin x \,dx $ por $ \int_0^\pi p(x)\,dx $ e determine
o erro associado. _Dica:_ Primeiro cote $ \vert \sin x - p(x) \vert $ usando
a fórmula para o erro no caderno anterior, depois use que
$ \big \vert \int_0^\pi \sin x\,dx - \int_0^\pi p(x)\,dx
\big \vert \le \int_0^\pi \vert \sin x - p(x) \vert\,dx $.

__Problema:__ Calcule o polinômio que interpola $ f(x) = e^x $ nos pontos 
$ x = -1, 0, 1, 2 $ na forma de Newton.

__Problema:__ A tabela abaixo exibe as temperaturas médias em uma cidade ao
longo do ano. Encontre o polinômio interpolador usando o método das diferenças
divididas de Newton e use-o para estimar a temperatura média em julho.
$$
   \begin{array}{c|c}
   \text{Mês} & \text{Temperatura (°C)} \\
   \hline
   \text{Janeiro} & 25 \\
   \text{Abril} & 20 \\
   \text{Junho} & 14 \\
   \text{Setembro} & 17 \\
   \end{array}
$$

## $ \S 5 $ Implementação da interpolação polinomial pelo método das diferenças divididas

In [6]:
def divided_differences(xs: list[float], ys: list[float]
                        )-> tuple[list[float], list[float]]:
    """
    Given a list of points, finds the coefficients of the interpolating polynomial
    using Newton's divided differences method.
    Parameters:
        * points: A list of tuples (x, y) representing the points to interpolate.
    Returns:
        * The x values of the input points.
        * The coefficients of the interpolating polynomial.
    """
    import numpy as np
    N = len(xs) - 1
    divided_diffs = np.zeros((N + 1, N + 1))
    divided_diffs[:, 0] = ys

    # Calculate the remaining divided differences:
    for j in range(1, N + 1):    # j is the order of the divided difference.
        for i in range(j, N + 1):
            divided_diffs[i][j] = (divided_diffs[i][j - 1]
                                   - divided_diffs[j - 1][j - 1])\
                                    / (xs[i] - xs[j - 1])
    return divided_diffs


def interpolate_polynomial(x: float, x_values: list[float], coefs: list[float]
                           ) -> float:
    """
    Given x, a list of x values, and a list of coefficients, computes the value
    of the interpolating polynomial at x using Newton's method.
    Parameters:
        * x: The value at which the interpolating polynomial is to be evaluated.
        * x_values: A list of x values of the input points.
        * coefs: A list of coefficients of the interpolating polynomial.
    Returns:
        The value of the interpolating polynomial at x.
    """
    n = len(coefs)
    result = coefs[-1]
    
    # Evaluate the interpolating polynomial at x using Newton's method:
    for i in range(n - 2, -1, -1):
        result = result * (x - x_values[i]) + coefs[i]
    return result


In [7]:
xs = [0, 1, 2]
ys = [0, 1, 4]
table = divided_differences(xs, ys)
print(table)

[[0. 0. 0.]
 [1. 1. 0.]
 [4. 2. 1.]]
