$ \DeclareMathOperator{\vol}{vol} $
$ \newcommand{\mbf}{\mathbf} $

# Integração de Monte Carlo

## $ \S 1 $ Introdução

Nas regras do trapézio e de Simpson, escolhemos $ N + 1 $ pontos $ x_0, x_1, \dots, x_N $ igualmente espaçados no intervalo de integração $ [a, b] $ como membros da "amostra" tomada para se estimar a integral de uma função $ f $.

Estes métodos são chamados de **determinísticos** porque o resultado fornecido é completamente determinado pelos parâmetros: uma vez fixados o número $ N + 1 $ de pontos e a função contínua $ f \colon [a, b] \to \mathbb R $, cada aplicação do método resulta no mesmo valor. Além disto, é possível determinar uma cota superior para o erro cometido em função de $ N $.

Em contraste, o método da *integração de Monte Carlo* que estudaremos neste caderno é **probabilístico**. A idéia  é escolher os pontos onde $ f $ será avaliada *aleatoriamente* dentro do intervalo $ [a, b] $. Desta forma cada aplicação fornece uma aproximação diferente, mesmo mantendo-se $ N $ fixo. Ademais, dado $ \varepsilon > 0 $, não podemos garantir que o erro envolvido na aproximação seja menor que $ \varepsilon $ para  $ N $ suficientemente grande; podemos apenas estimar a *probabilidade* que isto aconteça como uma função de $ N $.

Na verdade a integração de Monte Carlo é um caso particular de um método muito mais geral e extremamente útil, amplamente empregado em Física, Química, Engenharia e outras áreas, o *método de Monte Carlo*.

 ## $ \S 2 $ Descrição do método de Monte Carlo
 
Por **método de Monte Carlo** entende-se uma classe de algoritmos que consistem da execução de um alto número $ N $ de *experimentos* ou *ensaios* e da análise estatística dos resultados para se obter conclusões numéricas. 

**Exemplo 1:** Considere o disco $ D $ em $ \mathbb R^2 $ de raio $ 1 $ e centro na origem, determinado pela desigualdade
$$
x^2 + y^2 \le 1\,.
$$
Este disco tem área $ \pi $ e está contido no quadrado $ Q $ de área $ 4 $ descrito por
$$
\lvert{x}\rvert \le 1\,, \quad \lvert{y}\rvert \le 1\,.
$$
A probabilidade que um ponto escolhido de forma uniformemente aleatória em $ Q $ esteja dentro do disco $ D $ é o quociente entre as áreas, 
$$
\frac{\text{área}(D)}{\text{área}(Q)} = \frac{\pi}{4}\,.
$$
Suponha que escolhamos aleatoriamente $ 1, 2, 3, \dots $ até um total de $ N $ pontos dentro de $ Q $, e seja $ n $ o número destes pontos pertencentes ao disco $ D $. Um teorema da Teoria da Probabilidade chamado de **Lei dos Grandes Números** implica que o quociente entre o número de "sucessos" $ n $ e o número total $ N $ de pontos na amostra tende à probabilidade do sucesso:
$$
\lim_{N \to \infty} \frac{n}{N} = \frac{\pi}{4}\,.
$$
Mais ainda, fixado $ \varepsilon > 0 $ positivo qualquer,
$$
\lim_{N \to \infty} \text{pr}\bigg(\Big\lvert \frac{n}{N} - \frac{\pi}{4}\Big\rvert \le  \varepsilon \bigg) = 1\,.
$$
Em palavras, a probabilidade que a fração entre o número de pontos dentro do disco ($ n $) e o número total de pontos ($ N $) difira de $ \frac{\pi}{4} $ por mais que $ \varepsilon $ *tende a zero* conforme o número de experimentos aumenta!

## $ \S 3 $ Implementação do método de Monte Carlo

A implementação do método de Monte Carlo genérico é muito simples:

In [1]:
def monte_carlo(ensaio, N):
    """
    Dada uma função 'ensaio' (a ser implementada separadamente pelo usuário)
    que simula um único experimento e o número N de experimentos a serem
    realizados, contamos o número n de sucessos e retornamos n / N. 
    'ensaio' deve ser uma função sem argumentos que retorna True ou False.
    """
    n = 0
    for _ in range(N):
        if ensaio():
            n += 1
            
    return n / N

📝 Para simular escolhas uniformemente aleatórias, utilizaremos os seguintes procedimentos do módulo `numpy.random`:
* `randint(a, b)` retorna um inteiro aleatório entre os inteiros $ a $ e $ b - 1 $ (inclusive);
* `rand()` retorna um float aleatório entre $ 0 $ e $ 1 $.

Em ambos os casos podemos também gerar um array de dimensões especificadas contendo números dos tipos acima.

**Exemplo 2:**

In [2]:
from numpy.random import rand, randint


# Gerando um inteiro aleatório entre 0 e 100:
print(randint(0, 101))
# Gerando um float aleatório entre 0 e 1:
print(rand())

25
0.045177057219597305


In [3]:
# Vetor com 5 coordenadas float aleatórias entre 0 e 1:
print(rand(5))

[0.77001304 0.63498027 0.23242754 0.26547423 0.73817822]


In [4]:
# Matriz 2x4 com entradas inteiras e aleatórias entre 0 e 9:
print(randint(0, 10, size=(2, 4)))

[[3 7 5 8]
 [7 9 5 4]]


In [5]:
# Matriz 3x3 com entradas float aleatórias entre 0 e 1:
print(rand(3, 3))

[[0.57129825 0.86439541 0.43582549]
 [0.58715002 0.68652058 0.61285999]
 [0.96964435 0.08829535 0.18998686]]


## $ \S 4 $ Sobre o significado do termo "uniformemente aleatório"

Seja $ \Omega $ um conjunto. Informalmente, a distribuição **uniforme** de probabilidade em $ \Omega $ é aquela que atribiu a cada um de seus elementos $ \omega \in \Omega $ (chamados de **eventos** neste contexto) a mesma probabilidade.

No caso em que $ \Omega $ é discreto e finito, digamos com $ N $ elementos, isto significa simplesmente que
$$
    \text{pr}(\omega) = \frac{1}{N} \qquad \text{para todo $ \omega \in \Omega $}.
$$
No caso contínuo, digamos em que $ \Omega $ é um subconjunto de $ \mathbb R $, o significado é que a probabilidade que um evento pertença a um subconjunto $ S \subset \Omega $ é dada por 
$$
    \frac{\text{comprimento}(S)}{\text{comprimento}(\Omega)} = \frac{\int_S 1\,dx}{\int_\Omega 1\,dx}\ .
$$
Nos casos que consideraremos, a integral no denominador será sempre positiva e finita. Analogamente para dimensões mais altas, com área, volume, etc. em lugar de comprimento.

Estritamente falando, por escolha *aleatória* entende-se uma escolha feita de acordo com uma distribuição qualquer de probabilidade, porém neste caderno suporemos sempre que a distribuição subjacente é *uniforme*.

## $ \S 5 $ Estimando $ \pi $ via método de Monte Carlo

**Exemplo 3:** Use o método de Monte Carlo e o Exemplo 1 para obter uma estimativa para o valor de $ \pi $.

*Solução:*

In [6]:
from numpy.random import rand


def pertence_ao_disco() -> bool:
    """ Define um ensaio que escolhe um ponto (x, y) aleatoriamente
        dentro do quadrado Q definido por
            |x| <= 1,    |y| <= 1
        e retorna True se o ponto pertence ao disco D ou False caso contrário.
    """
    # 'esticar' transforma o intervalo [0, 1] no intervalo [-1, 1]:
    esticar = lambda x: 2 * x - 1
    # Escolha números aleatórios x, y entre -1 e 1.
    # Recorde que rand() escolhe um float aleatório em [0, 1].
    x = esticar(rand())
    y = esticar(rand())
    
    # Retorne True se x**2 + y**2 <= 1 e False caso contrário:
    return x**2 + y**2 <= 1

In [7]:
from numpy import pi


N = 10**5
estimativa = 4 * monte_carlo(pertence_ao_disco, N)

print(f"Valor de pi fornecido pelo NumPy: {pi}")
print(f"Estimativa obtida pelo método de Monte Carlo: {estimativa}")
print("A cada vez que executamos a célula, obtemos um resultado diferente!")

Valor de pi fornecido pelo NumPy: 3.141592653589793
Estimativa obtida pelo método de Monte Carlo: 3.14396
A cada vez que executamos a célula, obtemos um resultado diferente!


📝 No exemplo anterior, realizar $ 10 $ conjuntos de $ 10^4 $ ensaios cada e depois tomar a média aritmética das $ 10 $ estimativas dá no mesmo que realizar um único conjunto de $ 10^5 $ ensaios, como fizemos.

Mais geralmente, como no método de Monte Carlo assumimos que cada ensaio é independente dos outros, não faz diferença se realizamos $ m $  conjuntos de $ N_1,\dots,N_m $ ensaios cada e depois tomamos a média ponderada (pelo número correspondente de ensaios) das $ m $ estimativas
$$
\frac{n_1}{N_1}\,, \quad \frac{n_2}{N_2}\,, \quad \cdots \quad \frac{n_m}{N_m}\,,
$$
ou se realizamos um único conjunto de $ N = N_1 + \cdots + N_m $ ensaios e calculamos o quociente do número de sucessos pelo número de ensaios. De fato:
$$
\frac{N_1\, \frac{n_1}{N_1} + N_2\, \frac{n_2}{N_2} + \cdots + N_m\, \frac{n_m}{N_m}}{N_1 + N_2 + \cdots + N_m} = \frac{n_1 + n_2 + \cdots + n_m}{N_1 + N_2 + \cdots + N_m}.
$$


**Problema 1:** Um teorema de E. Cèsaro (1850—1906) diz que a probabilidade de dois naturais escolhidos ao acaso serem relativamente primos é de $ \frac{6}{\pi^2} $. (Dois inteiros $ m $ e $ n $ são *relativamente primos* caso $ \text{mdc}(m, n) = 1 $.)

(a) Construa um experimento que escolhe dois números aleatórios $ m $ e $ n $ entre $ 1 $ e $ 10^6 $ e retorna `True` caso eles sejam relativamente primos ou `False` caso contrário.

(b) Use o método de Monte Carlo e o teorema citado para obter uma aproximação para $ \pi $.

*Solução:*

In [ ]:
from numpy import sqrt, pi
from numpy.random import randint


def mdc(a, b):
    """Retorna o mdc de dois inteiros a, b. """
    assert isinstance(a, int) and isinstance(b, int)
    if b == 0:
        return a
    else:
        return mdc(b, a % b)

📝 O método de Monte Carlo é especialmente conveniente para o cálculo de áreas e volumes de regiões definidas através de desigualdades.

**Problema 2:** Usando o método de Monte Carlo, calcule o volume $ V $ da região sólida $ S $ em $ \mathbb R^3 $ determinada pelas desigualdades
$$
0 \le x \le y \le z \le 1
$$
com um erro menor que $ 10^{-3} $. *Dica:* Primeiramente monte um ensaio que escolhe aleatoriamente um ponto $ (x, y, z) $ dentro do cubo definido por $ 0 \le x,\,y,\,z \le 1 $ e decide se este ponto pertence a $ S $.

*Solução:*

## $ \S 6 $ Aplicação a integrais de funções de uma variável

Recorde do curso de Cálculo 1 que a integral
$$
\int_a^b f(x)\,dx
$$
é aproximada por *somas de Riemann*
$$
\sum_{i=1}^N f(\xi_i) \Delta_i
$$
onde
$$
[x_0, x_1],\ [x_1, x_2],\ \dots,\ [x_{N-1}, x_{N}]
$$
formam uma partição de $ [a, b] $,
$$
\Delta_i = x_i - x_{i-1}
$$
e os pontos
$$
\xi_i \in [x_{i-1}, x_i] \qquad (i = 1, \dots, N)
$$
podem ser escolhidos arbitrariamente. De fato, a integral é *definida* como o limite de somas deste tipo conforme o maior dos comprimentos $ \Delta_i $ vai a zero.

Considere o caso especial em que $ \Delta_i = \frac{b-a}{N} $ para cada $ i $, ou seja, os pontos são
$$
x_i = a +  i\,\frac{b-a}{N}
$$
e estão igualmente espaçados. Então a soma de Riemann se reduz a 
$$
\frac{b-a}{N}\sum_{i=1}^N f(\xi_i) = (b - a)\bigg(\frac{1}{N}\sum_{i=1}^Nf(\xi_i)\bigg)\,.
$$    
O último termo entre parênteses aqui pode ser visto como a média aritmética de uma amostra de $ N $ valores de $ f $ no intervalo, sujeitos à condição que o $ i $-ésimo ponto deve pertencer ao $ i $-ésimo intervalo da partição.

Suponha agora que os pontos $ \xi_i $ ($ i = 1, \dots, N $) sejam escolhidos *aleatoriamente* dentro de $ [a, b] $, sem qualquer restrição (ou seja, não imporemos que $ \xi_i $ pertença a $ [x_{i-1}, x_i] $). A Lei dos Grandes Números ainda garante que
$$
(b-a) \bigg(\frac{1}{N}\sum_{i=1}^Nf(\xi_i)\bigg) \longrightarrow \int_a^b f(x)\,dx \qquad \text{conforme }N \to \infty.
$$
A **integração de Monte Carlo** consiste da aproximação da integral à direita pelo valor à esquerda.

## $ \S 7 $ Implementação da integração de Monte Carlo em 1 dimensão

In [ ]:
def int_monte_carlo(f, a, b, N):
    """
    Calcula a integral de uma função f : [a, b] -> R 
    usando o método de Monte Carlo com N ensaios.
    """
    from numpy.random import rand
    
    # Transforma linearmente o intervalo [0, 1] no intervalo [a, b]:
    esticar = lambda x: a + (b - a) * x
    
    soma = 0
    for _ in range(N):
        x = esticar(rand())
        soma += f(x)
    
    return (b - a) * soma / N

**Problema 3:** Recorde que
$$
\int_0^1 \frac{1}{1+x^2}\,dx = \arctan(1) - \arctan(0)  = \frac{\pi}{4}\,.
$$
Use a integração de Monte Carlo para obter uma estimativa para $ \pi $.

*Solução:*

In [ ]:
from numpy import pi

## $ \S 8 $ Integração de Monte Carlo em qualquer dimensão

Para o cálculo de integrais definidas de funções de apenas uma variável, os métodos determinísticos como a regra de Simpson devem ser preferidos em relação à integração de Monte Carlo, por fornecerem resultados mais precisos com uso bem menor de recursos computacionais.

Contudo, em dimensões altas os métodos determinísticos não funcionam tão bem. A primeira dificuldade é que o número de operações necessárias aumenta rapidamente com a dimensão. Grosso modo, se para garantir uma determinada precisão eram necessárias $ N $ avaliações em dimensão $ 1 $, em dimensão $ 3 $ serão necessárias $ N^3 $. Outro obstáculo é que, enquanto em dimensão $ 1 $ quase sempre integramos sobre um intervalo, em dimensões $ \ge 2 $ a fronteira da região onde será calculada a integral pode ser muito mais complicada.

Seja
$$
f \colon D \to \mathbb R 
$$
uma função contínua de $ m $ variáveis $ x_1, \dots, x_m $ definida num domínio $ D $ qualquer de $ \mathbb R^m $, e seja $ R \subset D $ uma região regular o suficiente para que o seu volume faça sentido e possa ser calculado. Escolha aleatoriamente $ N $ pontos $ \boldsymbol{\xi_1}, \dots, \boldsymbol{\xi_N} $ dentro de $ R $. Pode-se mostrar que
$$
\vol(R)\,\bigg(\frac{1}{N}\sum_{i=1}^Nf(\boldsymbol{\xi_i})\bigg) \longrightarrow \int \int \cdots \int_R f(x_1,\,x_2,\cdots,x_m)\,\,dx_1\,dx_{2}\,\cdots dx_m \qquad \text{conforme }N \to \infty.
$$
O **método de integração de Monte Carlo** consiste da aproximação da integral múltipla à direita pela quantidade à esquerda.

## $ \S 9 $ Implementação da integração de Monte Carlo em qualquer dimensão

In [ ]:
def integracao_monte_carlo(f, dimensao, volume, N, escolhe_ponto):
    """
    Aproxima a integral de uma função f através do método de Monte Carlo.
    Entradas:
        * Uma função real f de uma ou mais variáveis.
        * A dimensão do domínio de f (número m de variáveis de f).
        * O volume da região R de integração.
        * O número N de pontos na amostra.
        * Uma função 'escolhe_ponto' sem argumentos que a cada chamada
          retorna um ponto em R escolhido aleatoriamente. O ponto
          deve ser representado como a lista de suas coordenadas.
    Saída: o valor aproximado da integral.
    """
    from numpy.random import rand
    from math import prod
    
    
    assert isinstance(N, int) and N >= 1
    assert isinstance(dimensao, int) and dimensao >= 1
    soma = 0
    for _ in range(N):
        x = escolhe_ponto()
        soma += f(*x)
    
    return volume * soma / N

📝 A notação `*x` na linha que atualiza a soma é usada para extrair as entradas de uma lista ou array `x`. Informalmente, ela
transforma $ [x_1, ..., x_m] $ em $ x_1, x_2, ..., x_m $ para que possamos
então aplicar a função $ f $ a estes argumentos. Esta operação é chamada de *unpacking* (desempacotamento). Estamos assumindo aqui que $ f $ tenha sido implementada como uma função de $ m $ variáveis, e não como função de uma variável que é uma lista ou array.

**Problema 4:** Estime a integral tripla
$$
    \int_{-1}^{2}\int_{-1}^2\int_{-1}^2 \cos\big(x\,y\,(2 - z^2)\big)\,dx\,dy\,dz
$$
usando a integração de Monte Carlo com uma amostra de $ N = 10^5 $ pontos. *Aviso:* Dependendo do computador, a resposta pode demorar um pouco. Não se preocupe com a precisão do resultado fornecido.

*Solução:*

In [ ]:
# Complete o esboço abaixo:


def escolhe_ponto():
    from numpy.random import rand
    
    esticar = lambda ...
    # Gerando um vetor aleatório em [0, 1] x [0, 1] x [0, 1]:
    ponto = ...
    # Transformando-no num vetor em [-1, 2] x [-1, 2] x [-1, 2]:
    ponto = ...
    
    return ponto


f = lambda ...
N = 10**5

<!---
## $ \S 7 $ Problema da agulha

Identifique o $ \mathbb R^2 $ com um pedaço de chão e suponha que as retas de equação
$$
x = 0\ , \quad x = \pm 1\ , \quad x = \pm 2\ , \dots, \quad x = \pm n\ , \quad \dots \qquad (n \in \mathbb N)
$$
estejam todas demarcadas. Jogamos uma agulha de comprimento $ c $ no chão de modo que sua posição e direção ao atingir um estado de repouso sejam determinadas aleatoriamente.

(a) Calcule a *probabilidade* de que a agulha cruze uma linha demarcada. Sua resposta deve depender apenas de $ c $.

*Dica:* Para facilitar as considerações, seja $ P = (x_0, y_0) $ a posição de um das pontas da agulha (escolhida uma vez por todas, antes do lançamento) e seja $ \theta \in [0, 2\pi) $ o ângulo que o vetor que liga esta ponta com a outra forma com o eixo-$x$ positivo. Podemos supor sem perda de generalidade que $ 0 \le x_0 \le 1 $. Note que o valor de $ y $ é irrelevante para se determinar se a agulha cruza uma linha demarcada. Determine o conjunto $ R $ de todos os pares
$$ (\theta, x(\theta)) $$
para os quais uma agulha de comprimento $ c $ com ponta inicial $ (x(\theta), y) $ formando um ângulo de $ \theta $ com o eixo-$ x $ positivo não cruza uma linha demarcada. A probabilidade será dada por
$$
\frac{\text{área}(R)}{2\pi}.
$$

(b) Use o método de Monte Carlo e o seu resultado do item (a) para estimar $ \pi $.
-->